
export const mockCategories = [
  {
    id: 1,
    name: 'Faciales',
    description: 'Tratamientos faciales para rejuvenecer y cuidar tu piel',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Corporales',
    description: 'Tratamientos corporales para relajarte y renovarte',
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Masajes',
    description: 'Masajes terapéuticos y relajantes',
    created_at: new Date().toISOString(),
  },
]

export const mockServices = [
  {
    id: 1,
    name: 'Limpieza Facial Profunda',
    description: 'Tratamiento facial que incluye extracción de impurezas, exfoliación y mascarilla hidratante para una piel radiante.',
    price: 65000,
    duration: 60,
    category_id: 1,
    image_url: 'https://www.esteticaeclipse.com/wp-content/uploads/2020/11/limpieza-facial-profunda-eclipse-pamplona-1-1.jpg',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Facial Anti-Edad',
    description: 'Tratamiento especializado con productos premium para reducir líneas de expresión y rejuvenecer la piel.',
    price: 85000,
    duration: 90,
    category_id: 1,
    image_url: 'https://esteticaavanzadasentiryser.com/wp-content/uploads/2023/10/hifu-facial-cuello-800x600.jpg',
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Hidrofacial',
    description: 'Tecnología avanzada que limpia, exfolia e hidrata profundamente para una piel luminosa al instante.',
    price: 95000,
    duration: 75,
    category_id: 1,
    image_url: 'https://sanjivamedspa.com/wp-content/uploads/2023/05/Hydrafacial-Sanjiva.png',
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Masaje Relajante',
    description: 'Masaje de cuerpo completo con aceites aromáticos para liberar tensiones y alcanzar un estado de relajación total.',
    price: 70000,
    duration: 60,
    category_id: 3,
    image_url: 'https://i.pinimg.com/736x/83/d3/b2/83d3b27f10bb6aff895e38bc37ad09f5.jpg',
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'Masaje Descontracturante',
    description: 'Masaje terapéutico dirigido a aliviar contracturas musculares y tensiones específicas del cuerpo.',
    price: 80000,
    duration: 75,
    category_id: 3,
    image_url: 'https://i.ytimg.com/vi_webp/35IDXqKYLFI/hqdefault.webp',
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'Exfoliación Corporal',
    description: 'Tratamiento completo de exfoliación e hidratación corporal que deja la piel suave y renovada.',
    price: 55000,
    duration: 45,
    category_id: 2,
    image_url: 'https://www.be-beauty.es/wp-content/uploads/2025/04/body-senses_foto-3.jpg',
    created_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: 'Envoltura Corporal',
    description: 'Tratamiento detoxificante y reafirmante con arcillas y algas marinas para renovar completamente tu piel.',
    price: 90000,
    duration: 90,
    category_id: 2,
    image_url: 'https://i1.wp.com/imabell.com/wp-content/uploads/2021/10/ALGA-MARINA.jpg?w=920&ssl=1',
    created_at: new Date().toISOString(),
  },
  {
    id: 8,
    name: 'Masaje con Piedras Calientes',
    description: 'Relajante masaje con piedras volcánicas calientes que ayudan a liberar tensiones profundas.',
    price: 85000,
    duration: 80,
    category_id: 3,
    image_url: 'https://www.solucionesnaturales.com.mx/cdn/shop/products/51poSY3csdL.jpg?v=1675960073&width=1445',
    created_at: new Date().toISOString(),
  },
]

export const availableTimeSlots = [
  '09:00',
  '10:00',
  '11:00',
  '12:00',
  '14:00',
  '15:00',
  '16:00',
  '17:00',
  '18:00',
]
